In [1]:
import pandas as pd

train = pd.read_pickle("../data/processed/train.pkl")
validation = pd.read_pickle("../data/processed/validation.pkl")
test = pd.read_pickle("../data/processed/test.pkl")

In [2]:
train.shape, validation.shape, test.shape

((473436, 15), (118664, 15), (121160, 15))

In [3]:
validation["naive_prediction"] = validation["lag_1"]

In [4]:
validation[["StockCode", "Date", "Demand", "lag_1", "naive_prediction", "target"]].head(
    15
)

     StockCode       Date  Demand  lag_1  naive_prediction  target
1036     10125 2011-08-20       0   20.0              20.0     0.0
1037     10125 2011-08-21       0    0.0               0.0     0.0
1038     10125 2011-08-22       0    0.0               0.0     0.0
1039     10125 2011-08-23       0    0.0               0.0    25.0
1040     10125 2011-08-24      25    0.0               0.0     0.0
1041     10125 2011-08-25       0   25.0              25.0     0.0
1042     10125 2011-08-26       0    0.0               0.0     0.0
1043     10125 2011-08-27       0    0.0               0.0     0.0
1044     10125 2011-08-28       0    0.0               0.0     0.0
1045     10125 2011-08-29       0    0.0               0.0     0.0
1046     10125 2011-08-30       0    0.0               0.0     0.0
1047     10125 2011-08-31       0    0.0               0.0     0.0
1048     10125 2011-09-01       0    0.0               0.0     0.0
1049     10125 2011-09-02       0    0.0               0.0     0.0
1050     10125 2011-09-03       0    0.0               0.0     0.0

In [6]:
from sklearn.metrics import mean_absolute_error

mae_naive = mean_absolute_error(validation["target"], validation["naive_prediction"])

mae_naive

11.302534888424459

In [7]:
from sklearn.metrics import mean_squared_error

rmse_naive = (
    mean_squared_error(validation["target"], validation["naive_prediction"]) ** 0.5
)

rmse_naive

49.119678713502225

In [8]:
zero_actual = validation["target"] == 0

zero_prediction_correct = (validation.loc[zero_actual, "naive_prediction"] == 0).mean()

zero_prediction_correct

np.float64(0.7388078031879823)

In [10]:
baseline_data = (
    pd.concat([train, validation, test], ignore_index=True)
    .sort_values(["StockCode", "Date"])
    .copy()
)

In [11]:
baseline_data["ma_7"] = baseline_data.groupby("StockCode")["Demand"].transform(
    lambda x: x.rolling(7).mean()
)

In [12]:
baseline_data[["StockCode", "Date", "Demand", "ma_7"]].head(15)

   StockCode       Date  Demand       ma_7
0      10002 2010-12-29       0        NaN
1      10002 2010-12-30       0        NaN
2      10002 2010-12-31       0        NaN
3      10002 2011-01-01       0        NaN
4      10002 2011-01-02       0        NaN
5      10002 2011-01-03       0        NaN
6      10002 2011-01-04       0   0.000000
7      10002 2011-01-05      12   1.714286
8      10002 2011-01-06      60  10.285714
9      10002 2011-01-07       1  10.428571
10     10002 2011-01-08       0  10.428571
11     10002 2011-01-09       0  10.428571
12     10002 2011-01-10       0  10.428571
13     10002 2011-01-11      24  13.857143
14     10002 2011-01-12       0  12.142857

In [13]:
baseline_data[["StockCode", "Date", "Demand", "ma_7", "target"]].head(15)

   StockCode       Date  Demand       ma_7  target
0      10002 2010-12-29       0        NaN     0.0
1      10002 2010-12-30       0        NaN     0.0
2      10002 2010-12-31       0        NaN     0.0
3      10002 2011-01-01       0        NaN     0.0
4      10002 2011-01-02       0        NaN     0.0
5      10002 2011-01-03       0        NaN     0.0
6      10002 2011-01-04       0   0.000000    12.0
7      10002 2011-01-05      12   1.714286    60.0
8      10002 2011-01-06      60  10.285714     1.0
9      10002 2011-01-07       1  10.428571     0.0
10     10002 2011-01-08       0  10.428571     0.0
11     10002 2011-01-09       0  10.428571     0.0
12     10002 2011-01-10       0  10.428571    24.0
13     10002 2011-01-11      24  13.857143     0.0
14     10002 2011-01-12       0  12.142857    11.0

In [14]:
validation_ma = baseline_data[
    (baseline_data["Date"] > "2011-08-19") & (baseline_data["Date"] <= "2011-10-12")
].copy()

validation_ma = validation_ma.dropna(subset=["ma_7", "target"])

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae_ma7 = mean_absolute_error(validation_ma["target"], validation_ma["ma_7"])

rmse_ma7 = mean_squared_error(validation_ma["target"], validation_ma["ma_7"]) ** 0.5

print("7-Day Moving Average MAE:", mae_ma7)
print("7-Day Moving Average RMSE:", rmse_ma7)

7-Day Moving Average MAE: 9.553136212849502
7-Day Moving Average RMSE: 37.12059034442131

In [17]:
model_features = [
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28",
    "rolling_mean_7",
    "rolling_std_7",
    "rolling_mean_28",
    "day_of_week",
    "month",
    "week_of_year",
    "is_weekend",
]

In [18]:
from sklearn.linear_model import LinearRegression

X_train = train[model_features]
y_train = train["target"]

X_validation = validation[model_features]
y_validation = validation["target"]

In [19]:
linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

LinearRegression()

In [20]:
linear_validation_pred = linear_model.predict(X_validation)

In [21]:
comparison = pd.DataFrame(
    {"Actual": y_validation.values, "Predicted": linear_validation_pred}
)

comparison.head(10)

   Actual  Predicted
0     0.0   1.558807
1     0.0   0.386629
2     0.0   5.445637
3    25.0   3.957255
4     0.0   2.468872
5     0.0   2.719063
6     0.0   1.579398
7     0.0   2.223451
8     0.0   0.735069
9     0.0   5.794077

In [22]:
print("Min prediction:", linear_validation_pred.min())
print("Max prediction:", linear_validation_pred.max())
print("Negative predictions:", (linear_validation_pred < 0).sum())

Min prediction: -7.820641066170015
Max prediction: 256.7697919950221
Negative predictions: 14854

In [23]:
mae_linear = mean_absolute_error(y_validation, linear_validation_pred)

rmse_linear = mean_squared_error(y_validation, linear_validation_pred) ** 0.5

print("Linear Regression MAE:", mae_linear)
print("Linear Regression RMSE:", rmse_linear)

Linear Regression MAE: 8.798927561624463
Linear Regression RMSE: 35.23593393973345

In [24]:
coefficients = pd.DataFrame(
    {"Feature": model_features, "Coefficient": linear_model.coef_}
).sort_values("Coefficient", ascending=False)

coefficients

            Feature  Coefficient
10       is_weekend     3.781816
4    rolling_mean_7     0.681176
6   rolling_mean_28     0.539987
8             month     0.298514
1             lag_7     0.007967
2            lag_14     0.005147
0             lag_1    -0.015810
3            lag_28    -0.016340
9      week_of_year    -0.089469
5     rolling_std_7    -0.280860
7       day_of_week    -1.488382

In [26]:
import xgboost as xgb

print(xgb.__version__)

3.2.0

In [27]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
)

In [28]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [29]:
xgb_validation_pred = xgb_model.predict(X_validation)

In [30]:
xgb_comparison = pd.DataFrame(
    {"Actual": y_validation.values, "Predicted": xgb_validation_pred}
)

xgb_comparison.head(10)

   Actual  Predicted
0     0.0   2.456470
1     0.0   3.223011
2     0.0   3.974154
3    25.0   3.977347
4     0.0   5.490889
5     0.0   5.102201
6     0.0  -0.103185
7     0.0   2.564731
8     0.0   4.480474
9     0.0   5.216669

In [31]:
print("Min prediction:", xgb_validation_pred.min())
print("Max prediction:", xgb_validation_pred.max())
print("Negative predictions:", (xgb_validation_pred < 0).sum())

Min prediction: -63.571396
Max prediction: 612.36365
Negative predictions: 4668

In [32]:
mae_xgb = mean_absolute_error(y_validation, xgb_validation_pred)

rmse_xgb = mean_squared_error(y_validation, xgb_validation_pred) ** 0.5

print("XGBoost MAE:", mae_xgb)
print("XGBoost RMSE:", rmse_xgb)

XGBoost MAE: 8.675399956501595
XGBoost RMSE: 35.58789610685837

In [33]:
xgb_results = pd.DataFrame(
    {"Actual": y_validation.values, "Predicted": xgb_validation_pred}
)

xgb_results["Error"] = xgb_results["Actual"] - xgb_results["Predicted"]

xgb_results["Absolute_Error"] = xgb_results["Error"].abs()

In [34]:
print(
    "Zero-demand MAE:",
    xgb_results.loc[xgb_results["Actual"] == 0, "Absolute_Error"].mean(),
)

print(
    "Non-zero demand MAE:",
    xgb_results.loc[xgb_results["Actual"] > 0, "Absolute_Error"].mean(),
)

Zero-demand MAE: 3.5264963060206465
Non-zero demand MAE: 18.31649177407204

In [35]:
high_demand = xgb_results[xgb_results["Actual"] >= 20]

print("High-demand observations:", len(high_demand))
print("High-demand MAE:", high_demand["Absolute_Error"].mean())
print("High-demand RMSE:", (high_demand["Error"] ** 2).mean() ** 0.5)

High-demand observations: 11782
High-demand MAE: 47.00839356266998
High-demand RMSE: 108.85909611036378

In [36]:
linear_results = pd.DataFrame(
    {"Actual": y_validation.values, "Predicted": linear_validation_pred}
)

linear_results["Error"] = linear_results["Actual"] - linear_results["Predicted"]

linear_results["Absolute_Error"] = linear_results["Error"].abs()

linear_high_demand = linear_results[linear_results["Actual"] >= 20]

print("High-demand observations:", len(linear_high_demand))
print("High-demand MAE:", linear_high_demand["Absolute_Error"].mean())
print("High-demand RMSE:", (linear_high_demand["Error"] ** 2).mean() ** 0.5)

High-demand observations: 11782
High-demand MAE: 46.16075144016594
High-demand RMSE: 108.76031881332261

In [37]:
zero_prediction = pd.Series(0, index=y_validation.index)

zero_mae = mean_absolute_error(y_validation, zero_prediction)

zero_rmse = mean_squared_error(y_validation, zero_prediction) ** 0.5

print("Zero Baseline MAE:", zero_mae)
print("Zero Baseline RMSE:", zero_rmse)

Zero Baseline MAE: 7.705673161194634
Zero Baseline RMSE: 37.840731405191534